version: "3.8"
services:
  frontend:
    build: 
      context: .
      dockerfile: frontend/docker/Dockerfile
    container_name: frontend
    ports:
      - '3008:3000'
  backend:
    build: 
      context: .
      dockerfile: backend/docker/Dockerfile
    container_name: backend
    ports:
      - '4000:4000'
    stdin_open: true
    tty: true